module hash.tools {
    requires javafx.fxml;
    requires javafx.controls;
    requires org.slf4j;

    exports hashtools;
    exports hashtools.backend.application.controller;
    exports hashtools.backend.application.service;
    exports hashtools.backend.checker.controller;
    exports hashtools.backend.checker.domain;
    exports hashtools.backend.checker.service;
    exports hashtools.backend.comparator.controller;
    exports hashtools.backend.comparator.domain;
    exports hashtools.backend.comparator.service;
    exports hashtools.backend.core.checksum;
    exports hashtools.backend.core.file;
    exports hashtools.backend.core.interfaces;
    exports hashtools.backend.core.strategy.algorithmsource;
    exports hashtools.backend.core.strategy.checksumsource;
    exports hashtools.backend.core.strategy.inputsource;
    exports hashtools.backend.core.strategy.threadpool;
    exports hashtools.backend.generator.controller;
    exports hashtools.backend.generator.domain;
    exports hashtools.backend.generator.service;
    exports hashtools.frontend.util;
    exports hashtools.frontend.window;

    opens hashtools;
    opens hashtools.backend.application.controller;
    opens hashtools.backend.application.service;
    opens hashtools.backend.checker.controller;
    opens hashtools.backend.checker.domain;
    opens hashtools.backend.checker.service;
    opens hashtools.backend.comparator.controller;
    opens hashtools.backend.comparator.domain;
    opens hashtools.backend.comparator.service;
    opens hashtools.backend.core.checksum;
    opens hashtools.backend.core.file;
    opens hashtools.backend.core.interfaces;
    opens hashtools.backend.core.strategy.algorithmsource;
    opens hashtools.backend.core.strategy.checksumsource;
    opens hashtools.backend.core.strategy.inputsource;
    opens hashtools.backend.core.strategy.threadpool;
    opens hashtools.backend.generator.controller;
    opens hashtools.backend.generator.domain;
    opens hashtools.backend.generator.service;
    opens hashtools.frontend.util;
    opens hashtools.frontend.window;
}
